services:
  api:
    image: doink/letrack-api:latest
    ports:
      - 5021:5021
    restart: unless-stopped
    environment:
      Config__MqttBroker: mqtt
      Config__MinLapTime: 3
      ConnectionStrings__DefaultConnection: host=db;database=letrack;username=letrack;password=letrack
    depends_on:
      - db
      - mqtt
    healthcheck:
      test: curl -f http://localhost:5021
      start_period: 30s

  fe:
    image: doink/letrack:latest
    ports:
      - 5173:80
    restart: unless-stopped
    environment:
      PUBLIC_API_URL: http://localhost:5021
    depends_on:
      - api
    healthcheck:
      test: curl -f http://localhost
      start_period: 30s

  db:
    image: postgres:17
    ports:
      - 5432:5432
    restart: unless-stopped
    environment:
      POSTGRES_DB: letrack
      POSTGRES_USER: letrack
      POSTGRES_PASSWORD: letrack
      PGUSER: letrack
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -d letrack
      start_period: 30s

  mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
    volumes:
      - ./api/conf/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto:/mosquitto/data
    restart: unless-stopped
    healthcheck:
      test: mosquitto_sub -i mosquitto-healthcheck -t mosquitto-healthcheck -E
      start_period: 30s

  ntp:
    image: cturra/ntp:latest
    restart: unless-stopped
    ports:
      - 123:123/udp
    environment:
      - NTP_SERVERS=time.cloudflare.com
      - LOG_LEVEL=3
volumes:
  pg-data:
  mosquitto:
