name: build fe
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  fe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: latest

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: pnpm
          cache-dependency-path: fe/pnpm-lock.yaml

      - name: Install Dependencies
        run: pnpm i
        working-directory: ./fe

      - name: Build
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: pnpm build
        working-directory: ./fe

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: LS
        run: ls -al
        working-directory: ./fe

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./fe
          push: true
          platforms: linux/amd64,linux/arm64
          tags: doink/letrack:latest, doink/letrack:${{ github.sha }}

  # api:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v3

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3

  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}

  #     - name: Build and push
  #       uses: docker/build-push-action@v5
  #       with:
  #         context: "{{defaultContext}}:api"
  #         push: true
  #         platforms: linux/amd64,linux/arm64
  #         tags: doink/letrack-api:latest, doink/letrack-api:${{ github.sha }}
